host: 0.0.0.0
port: 8080

public_url: https://lb-api.wds-stellarium.com
server_version: "2.31.0"
asset_version: "2.31.0"
master_data_version: ""
master_data_uri: ""
master_data_sas_token: ""
master_data_publish_timestamp: ""
feature_maintenance_flags: ""
maintenance: false
