KEYS = {
    "AbilityVarietyUpPayload": (
        (0, "photo_id", "long", False, "prim"),
        (1, "variety_to", "int", False, "prim"),
        (2, "item_master_id", "long", False, "prim"),
    ),
    "AccessoryAutoSellConvertThing": (
        (0, "accessory_master_id", "long", False, "prim"),
        (1, "convert_thing", "ReceivedThing", False, "model"),
    ),
    "AccessoryFavoritePayload": (
        (0, "accessory_id", "long", False, "prim"),
        (1, "set_favorite", "bool", False, "prim"),
    ),
    "AccountConnectPayload": (
        (0, "provider", "AuthenticationProviders", False, "enum"),
        (1, "token", "string", False, "prim"),
    ),
    "AccountDeletionResult": (
        (0, "is_success", "bool", False, "prim"),
        (1, "error", "AccountDeletionErrorTypes", False, "enum"),
    ),
    "AccountRegistResult": (
        (0, "token", "string", False, "prim"),
        (1, "error_type", "AccountRegisterErrorTypes", False, "enum"),
    ),
    "AcquirableThing": (
        (0, "id_", "long", False, "prim"),
        (1, "quantity", "int", False, "prim"),
    ),
    "AcquirableThingsPayload": ((0, "things", "AcquirableThing", True, "model"),),
    "ActorPortalCharacterPayload": (
        (0, "character_base_id", "long", False, "prim"),
        (1, "character_id", "long", False, "prim"),
        (2, "is_awakening", "bool", False, "prim"),
    ),
    "AlbumArrangingPayload": (
        (0, "publishing", "bool", False, "prim"),
        (1, "page", "int", False, "prim"),
        (2, "items", "byte", True, "prim"),
        (3, "m_album_theme_id", "long", False, "prim"),
    ),
    "AlbumPageResult": (
        (0, "album_page_id", "long", False, "prim"),
        (1, "album_id", "long", False, "prim"),
        (2, "level", "int", False, "prim"),
        (3, "page", "int", False, "prim"),
        (4, "edit_type", "EditTypes", False, "enum"),
        (5, "publishing", "bool", False, "prim"),
        (6, "items", "byte", True, "prim"),
        (7, "album_theme_master_id", "long", False, "prim"),
    ),
    "AlbumPageSearchResult": (
        (0, "album_page_result", "AlbumPageResult", False, "model"),
        (1, "is_success", "bool", False, "prim"),
    ),
    "AlbumPhotoPayload": (
        (0, "photo_id", "long", False, "prim"),
        (1, "order", "int", False, "prim"),
    ),
    "AuditionClearParty": (
        (0, "id_", "long", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "difficulty", "MusicDifficulties", False, "enum"),
        (3, "slots", "AuditionClearPartySlot", True, "model"),
        (4, "user_name", "string", False, "prim"),
        (5, "rate_grade", "AchievementRateGrades", False, "enum"),
        (9, "player_rank", "string", False, "prim"),
        (10, "leader_position", "int", False, "prim"),
    ),
    "AuditionClearPartySlot": (
        (0, "position", "int", False, "prim"),
        (1, "character_master_id", "long", False, "prim"),
        (2, "character_level", "int", False, "prim"),
        (3, "character_talent_stage", "int", False, "prim"),
        (4, "character_awakening_phase", "int", False, "prim"),
        (5, "poster_master_id", "long", False, "prim"),
        (6, "poster_level", "int", False, "prim"),
        (7, "poster_breakthrough_phase", "int", False, "prim"),
        (8, "accessory_master_id", "long", False, "prim"),
        (9, "accessory_level", "int", False, "prim"),
        (10, "star_rank", "int", False, "prim"),
        (11, "talent_stage", "int", False, "prim"),
        (12, "awakening_phase", "long", False, "prim"),
        (13, "current_status", "Status", False, "model"),
        (14, "character_display_awakening_status", "bool", False, "prim"),
    ),
    "AuditionClearedInformationParties": (
        (0, "parties", "AuditionClearParty", True, "model"),
        (1, "cleared_phase", "byte", False, "prim"),
    ),
    "AuditionClearedInformationResult": (
        (0, "parties_phases", "AuditionClearedInformationParties", True, "model"),
    ),
    "AuthenticatePayload": (
        (0, "login_token", "string", False, "prim"),
        (1, "game_version", "GameVersions", False, "enum"),
        (2, "apk_hash", "string", False, "prim"),
        (3, "apk_application_signature", "string", False, "prim"),
        (4, "application_version", "string", False, "prim"),
    ),
    "AuthenticateResult": (
        (0, "token", "string", False, "prim"),
        (1, "ban_level", "BanLevels", False, "enum"),
        (2, "warned_until", "DateTime", False, "prim"),
    ),
    "BannerPayload": (
        (0, "circle_hashed_id", "string", False, "prim"),
        (1, "poster_master_id", "long", False, "prim"),
        (2, "x1", "float", False, "prim"),
        (3, "y1", "float", False, "prim"),
        (4, "x2", "float", False, "prim"),
        (5, "y2", "float", False, "prim"),
        (6, "rotation_angle", "int", False, "prim"),
        (7, "display_poster_string", "bool", False, "prim"),
        (8, "banner_ratio", "float", False, "prim"),
    ),
    "BaseScoreBlock": (
        (0, "hash", "long", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "life", "int", False, "prim"),
        (3, "note_id", "long", False, "prim"),
        (4, "timing_type", "TimingTypes", False, "enum"),
        (5, "combo", "int", False, "prim"),
    ),
    "BlockListResult": ((0, "results", "FriendResult", True, "model"),),
    "BonusLiveResult": ((0, "rewards", "ReceivedThing", True, "model"),),
    "BooleanResult": ((0, "is_success", "bool", False, "prim"),),
    "BulkLevelUpPayload": (
        (0, "character_id", "long", False, "prim"),
        (1, "order", "int", False, "prim"),
    ),
    "BulkReceivePayload": ((0, "inbox_ids", "long", True, "prim"),),
    "CalculateLessonTimeEventPayload": (
        (0, "music_master_id", "long", False, "prim"),
        (1, "character_base_master_id", "long", False, "prim"),
    ),
    "CalculateTimeEventPayload": (
        (0, "music_master_id", "long", False, "prim"),
        (1, "sense_notation_master_id", "long", False, "prim"),
        (2, "party_id", "long", False, "prim"),
        (3, "vocal_version", "int", False, "prim"),
        (4, "is_story_event_challenge", "bool", False, "prim"),
    ),
    "ChangeNamePayload": ((0, "name", "string", False, "prim"),),
    "ChangePhotoAbilityPayload": (
        (0, "photo_id", "long", False, "prim"),
        (1, "item_master_id", "long", False, "prim"),
        (2, "photo_effect_type_group_master_id", "long", False, "prim"),
    ),
    "CharacterBaseStarPointResult": (
        (0, "character_base_master_id", "long", False, "prim"),
        (1, "star_point_result", "StarPointResult", False, "model"),
        (2, "link_character_received_reward", "ReceivedThing", True, "model"),
    ),
    "CharacterFavoritePayload": (
        (0, "character_id", "long", False, "prim"),
        (1, "set_favorite", "bool", False, "prim"),
    ),
    "CharacterLineupResult": (
        (0, "normal_probabilities", "CharacterRarityProbability", True, "model"),
        (1, "fixed_probabilities", "CharacterRarityProbability", True, "model"),
        (2, "normal_lineup_items", "GachaLineupItemProbability", True, "model"),
        (3, "fixed_lineup_items", "GachaLineupItemProbability", True, "model"),
    ),
    "CharacterPointEventInformationResult": (
        (0, "current_total_point", "long", False, "prim"),
        (1, "overall_rank", "int", False, "prim"),
        (2, "character_rank", "int", False, "prim"),
    ),
    "CharacterPointEventRankingResult": (
        (0, "raw_ranking", "RawRankingWithLongPoint", True, "model"),
        (1, "user_profiles", "UserProfile", True, "model"),
    ),
    "CharacterRank": (
        (0, "m_character_base_id", "long", False, "prim"),
        (1, "rank", "int", False, "prim"),
    ),
    "CharacterRarityProbability": (
        (0, "rarity", "CharacterRarities", False, "enum"),
        (1, "probability", "double", False, "prim"),
    ),
    "ChatworkSendMessagePayload": ((0, "message", "string", False, "prim"),),
    "CircleAuthorityChangePayload": (
        (0, "circle_hashed_id", "string", False, "prim"),
        (1, "user_id", "string", False, "prim"),
        (2, "authority", "CircleAuthorities", False, "enum"),
    ),
    "CircleAuthorityResult": (
        (0, "result_status", "CircleAuthorityResultStatus", False, "enum"),
    ),
    "CircleBanner": (
        (0, "poster_master_id", "long", False, "prim"),
        (1, "x1", "float", False, "prim"),
        (2, "y1", "float", False, "prim"),
        (3, "x2", "float", False, "prim"),
        (4, "y2", "float", False, "prim"),
        (5, "rotation_angle", "int", False, "prim"),
        (6, "display_poster_string", "bool", False, "prim"),
        (7, "banner_ratio", "float", False, "prim"),
    ),
    "CircleEventCircleMissionProgress": (
        (0, "circle_event_mission_master_id", "long", False, "prim"),
        (1, "current_count", "long", False, "prim"),
    ),
    "CircleEventInformationResult": (
        (0, "circle_point", "long", False, "prim"),
        (1, "user_point", "long", False, "prim"),
        (2, "last_received_circle_point", "long", False, "prim"),
        (3, "mission_refresh_count", "int", False, "prim"),
        (4, "progresses", "CircleEventCircleMissionProgress", True, "model"),
    ),
    "CircleEventRanking": (
        (0, "circle_raw_rankings", "CircleRawRanking", True, "model"),
        (1, "circle_profiles", "CircleProfile", True, "model"),
    ),
    "CircleInformationResult": (
        (0, "u_circle_hashed_id", "string", False, "prim"),
        (1, "name", "string", False, "prim"),
        (2, "comment", "string", False, "prim"),
        (3, "play_time_start_type", "PlayTimeTypes", False, "enum"),
        (4, "play_time_end_type", "PlayTimeTypes", False, "enum"),
        (5, "entry_type", "EntryTypes", False, "enum"),
        (6, "member_count", "int", False, "prim"),
        (7, "invite_id", "long", False, "prim"),
        (9, "result_status", "CircleResultStatus", False, "enum"),
        (10, "circle_banner", "CircleBanner", False, "model"),
        (11, "main_character_master_id", "long", False, "prim"),
        (12, "display_awakening_status", "bool", False, "prim"),
        (13, "company_master_id", "long", False, "prim"),
        (14, "character_base_master_id", "long", False, "prim"),
        (15, "icon_fame_master_id", "long", False, "prim"),
    ),
    "CircleInviteResult": (
        (0, "result_status", "CircleResultStatus", False, "enum"),
        (1, "invite_id", "long", False, "prim"),
    ),
    "CircleMemberInfoParameters": (
        (0, "user_id", "string", False, "prim"),
        (1, "user_name", "string", False, "prim"),
        (2, "player_rank", "int", False, "prim"),
        (3, "last_login_at", "DateTime", False, "prim"),
        (4, "authority", "CircleAuthorities", False, "enum"),
        (5, "main_u_character", "MainCharacter", False, "model"),
        (6, "invite_id", "long", False, "prim"),
        (7, "request_id", "long", False, "prim"),
        (8, "trophy_master_id1", "long", False, "prim"),
        (9, "trophy_master_id2", "long", False, "prim"),
        (10, "trophy_master_id3", "long", False, "prim"),
        (11, "main_character_master_id", "long", False, "prim"),
        (12, "display_awakening_status", "bool", False, "prim"),
        (13, "player_rate", "Decimal", False, "model"),
        (14, "is_public_player_rate", "bool", False, "prim"),
        (15, "league_class", "LeagueClassTypes", False, "enum"),
        (16, "icon_fame_master_id", "long", False, "prim"),
    ),
    "CircleMemberInfoResult": (
        (0, "parameters", "CircleMemberInfoParameters", True, "model"),
        (1, "result_status", "CircleResultStatus", False, "enum"),
        (2, "circle_banner", "CircleBanner", False, "model"),
    ),
    "CircleMemberParameters": (
        (0, "user_id", "string", False, "prim"),
        (1, "user_name", "string", False, "prim"),
        (2, "player_rank", "int", False, "prim"),
        (3, "last_login_at", "DateTime", False, "prim"),
        (4, "authority", "CircleAuthorities", False, "enum"),
        (5, "main_u_character", "MainCharacter", False, "model"),
        (6, "invite_id", "long", False, "prim"),
        (7, "request_id", "long", False, "prim"),
        (8, "trophy_master_id1", "long", False, "prim"),
        (9, "trophy_master_id2", "long", False, "prim"),
        (10, "trophy_master_id3", "long", False, "prim"),
        (11, "main_character_master_id", "long", False, "prim"),
        (12, "display_awakening_status", "bool", False, "prim"),
        (16, "icon_fame_master_id", "long", False, "prim"),
    ),
    "CirclePayload": (
        (0, "hashed_id", "string", False, "prim"),
        (1, "name", "string", False, "prim"),
        (2, "comment", "string", False, "prim"),
        (3, "play_time_start_type", "PlayTimeTypes", False, "enum"),
        (4, "play_time_end_type", "PlayTimeTypes", False, "enum"),
        (5, "entry_type", "EntryTypes", False, "enum"),
        (6, "member_type", "SearchCircleMemberConditionTypes", False, "enum"),
        (7, "company_master_id", "long", False, "prim"),
        (8, "character_base_master_id", "long", False, "prim"),
    ),
    "CircleProfile": (
        (0, "circle_id", "string", False, "prim"),
        (1, "name", "string", False, "prim"),
        (2, "member_count", "int", False, "prim"),
        (3, "main_character_master_id", "long", False, "prim"),
        (4, "display_awakening_status", "bool", False, "prim"),
        (5, "icon_frame_master_id", "long", False, "prim"),
    ),
    "CircleRawRanking": (
        (0, "rank", "int", False, "prim"),
        (1, "point", "int", False, "prim"),
        (2, "circle_id", "string", False, "prim"),
    ),
    "CircleResult": ((0, "result_status", "CircleResultStatus", False, "enum"),),
    "CircleSearchIdResult": (
        (0, "parameters", "CircleMemberParameters", False, "model"),
        (1, "result_status", "CircleResultStatus", False, "enum"),
    ),
    "CircleSearchResult": (
        (0, "parameters", "CircleMemberParameters", True, "model"),
        (1, "result_status", "CircleResultStatus", False, "enum"),
        (2, "circle_banner", "CircleBanner", False, "model"),
    ),
    "ConcertResult": ((0, "rewards", "ReceivedThing", True, "model"),),
    "ConcoursDetailInformationResult": (
        (0, "concours_detail_master_id", "long", False, "prim"),
        (1, "rank", "int", False, "prim"),
    ),
    "ConcoursInfomationResult": (
        (0, "details", "ConcoursDetailInformationResult", True, "model"),
        (1, "current_point", "int", False, "prim"),
    ),
    "ConvertedThingResult": (
        (0, "exchange_shop_master_id", "long", False, "prim"),
        (1, "original_quantity", "int", False, "prim"),
        (2, "received_thing", "ReceivedThing", False, "model"),
    ),
    "CostumeFavoritePayload": (
        (0, "costume_master_id", "long", False, "prim"),
        (1, "character_base_master_id", "long", False, "prim"),
        (2, "set_favorite", "bool", False, "prim"),
    ),
    "CourseRankingResult": (
        (0, "rank", "int", False, "prim"),
        (1, "user_id", "long", False, "prim"),
        (2, "user_profile", "UserProfile", False, "model"),
        (3, "course_result", "CourseResult", False, "model"),
        (4, "note_result", "NoteResult", False, "model"),
    ),
    "CourseResult": (
        (0, "total_achievement_rate_percent_record", "Decimal", False, "model"),
        (1, "best_record_challenge_count", "int", False, "prim"),
        (2, "best_record_date", "DateTime", False, "prim"),
    ),
    "CreateCircleResult": (
        (0, "result_status", "CircleResultStatus", False, "enum"),
        (1, "circle_hashed_id", "string", False, "prim"),
    ),
    "CreateMultiRoomPayload": (
        (0, "room_name", "string", False, "prim"),
        (1, "password", "string", False, "prim"),
        (2, "can_join_max_member", "int", False, "prim"),
        (3, "start_date", "DateTime", False, "prim"),
        (4, "end_date", "DateTime", False, "prim"),
        (5, "play_mode", "MultiRoomPlayModes", False, "enum"),
        (6, "live_master_id1", "long", False, "prim"),
        (7, "live_master_id2", "long", False, "prim"),
        (8, "live_master_id3", "long", False, "prim"),
    ),
    "DebugAlbumSimpleArrangingPayload": (
        (0, "publishing", "bool", False, "prim"),
        (1, "page", "int", False, "prim"),
        (2, "photos", "AlbumPhotoPayload", True, "model"),
        (3, "m_album_theme_id", "long", False, "prim"),
    ),
    "DebugEditLeagueBasicPayload": (
        (0, "current_class_type", "LeagueClassTypes", False, "enum"),
        (1, "best_class_type", "LeagueClassTypes", False, "enum"),
    ),
    "DebugLinkageCodeResult": (
        (0, "password", "string", False, "prim"),
        (1, "take_over_code_result", "TakeOverCodeResult", False, "model"),
    ),
    "DebugModifyCharacterEnhanceInformationPayload": (
        (0, "m_character_id", "long", False, "prim"),
        (1, "actor_level", "int", False, "prim"),
        (2, "is_awaken", "bool", False, "prim"),
        (3, "sense_level", "int", False, "prim"),
        (4, "talent_bloom_stage", "int", False, "prim"),
    ),
    "DebugModifyPosterEnhanceInformationPayload": (
        (0, "m_poster_id", "long", False, "prim"),
        (1, "level", "int", False, "prim"),
        (2, "release_phase", "int", False, "prim"),
    ),
    "DebugPrepareLeagueGroupUserPayload": (
        (0, "league_master_id", "long", False, "prim"),
        (1, "class_type", "LeagueClassTypes", False, "enum"),
        (2, "user_ids", "long", True, "prim"),
    ),
    "DebugUserIdResult": (
        (0, "user_id", "string", False, "prim"),
        (1, "hashed_user_id", "string", False, "prim"),
    ),
    "Decimal": (),
    "Dictionary": (),
    "DonateSupportCompanyResult": (
        (0, "my_circle_information", "MyCircleInformationResult", False, "model"),
        (1, "result_status", "CircleDonateSupportCompanyResult", False, "enum"),
    ),
    "DonateSupportLevelLimitDetail": (
        (0, "order", "int", False, "prim"),
        (1, "quantity", "int", False, "prim"),
    ),
    "DonateSupportLevelLimitPayload": (
        (0, "company", "Companies", False, "enum"),
        (1, "next_level_limit", "int", False, "prim"),
        (2, "coin_quantity", "int", False, "prim"),
        (3, "details", "DonateSupportLevelLimitDetail", True, "model"),
    ),
    "EditBookmarkPayload": (
        (0, "music_master_id", "long", False, "prim"),
        (1, "bookmark_flag", "MusicBookmarkFlags", False, "enum"),
    ),
    "EditPartyPayload": (
        (0, "party_slots", "EditPartySlotPayload", True, "model"),
        (1, "sense_notation_master_id", "long", False, "prim"),
        (2, "music_master_id", "long", False, "prim"),
        (3, "vocal_version", "int", False, "prim"),
        (4, "is_high_score_challenge", "bool", False, "prim"),
        (5, "leader_position", "int", False, "prim"),
    ),
    "EditPartySlotPayload": (
        (0, "u_party_slot_id", "long", False, "prim"),
        (1, "u_character_id", "long", False, "prim"),
        (2, "u_accessory_id", "long", False, "prim"),
        (3, "u_poster_id", "long", False, "prim"),
        (4, "bonus_ability_enable_flags", "BonusAbilityEnableFlags", False, "enum"),
    ),
    "EditPositionPayload": ((0, "slots", "EditPositionSlotPayload", True, "model"),),
    "EditPositionSlotPayload": (
        (0, "u_party_slot_id", "long", False, "prim"),
        (1, "position", "int", False, "prim"),
    ),
    "EditTrialPartyEventStagePartyPayload": (
        (0, "trial_party_event_stage_master_id", "long", False, "prim"),
        (1, "slots", "EditTrialPartyEventStagePartyPayloadSlot", True, "model"),
        (2, "leader_position", "int", False, "prim"),
    ),
    "EditTrialPartyEventStagePartyPayloadSlot": (
        (0, "position", "int", False, "prim"),
        (1, "trial_party_character_master_id", "long", False, "prim"),
        (2, "trial_party_poster_master_id", "long", False, "prim"),
        (3, "trial_party_accessory_master_id", "long", False, "prim"),
    ),
    "EditUserProfilePayload": (
        (0, "name", "string", False, "prim"),
        (1, "introduction", "string", False, "prim"),
        (2, "main_u_character_id", "long", False, "prim"),
        (3, "m_nameplate_id", "long", False, "prim"),
        (4, "m_name_color_id", "long", False, "prim"),
        (5, "m_trophy_id1", "long", False, "prim"),
        (6, "m_trophy_id2", "long", False, "prim"),
        (7, "m_trophy_id3", "long", False, "prim"),
        (8, "is_public_player_rate", "bool", False, "prim"),
        (9, "display_awakening_status", "bool", False, "prim"),
        (10, "main_character_master_id", "long", False, "prim"),
        (11, "name_base_color_masterid", "long", False, "prim"),
        (12, "icon_frame_master_id", "long", False, "prim"),
        (13, "home_skin_master_id", "long", False, "prim"),
    ),
    "EexternalPaymentResult": (
        (0, "received_jewel_shop_item_master_ids", "long", True, "prim"),
    ),
    "Effect": (
        (0, "order", "int", False, "prim"),
        (1, "master_id", "long", False, "prim"),
        (2, "effect_types", "EffectTypes", False, "enum"),
        (3, "triggers", "EffectTrigger", True, "model"),
        (4, "targets", "EffectTargetValue", True, "model"),
        (5, "duration", "int", False, "prim"),
    ),
    "EffectBranch": (
        (0, "condition_value", "long", False, "prim"),
        (1, "judge_types", "BranchJudgeTypes", False, "enum"),
        (2, "sense_effects", "Effect", True, "model"),
    ),
    "EffectTargetValue": (
        (0, "target_actor_id", "long", False, "prim"),
        (1, "value", "double", False, "prim"),
    ),
    "EffectTrigger": (
        (0, "type", "TriggerTypes", False, "enum"),
        (1, "value", "long", False, "prim"),
    ),
    "EnvironmentResult": (
        (0, "application_version", "string", False, "prim"),
        (1, "asset_version", "string", False, "prim"),
        (2, "api_endpoint", "string", False, "prim"),
        (3, "maintenance_api_endpoint", "string", False, "prim"),
        (4, "news_api_endpoint", "string", False, "prim"),
        (5, "is_maintenance", "bool", False, "prim"),
        (6, "master_data_url", "string", False, "prim"),
        (7, "static_content_url", "string", False, "prim"),
        (8, "asset_url", "string", False, "prim"),
        (9, "is_app_review", "bool", False, "prim"),
        (10, "photo_content_url", "string", False, "prim"),
        (11, "multi_real_time_server_url", "string", False, "prim"),
        (12, "external_payment_url", "string", False, "prim"),
    ),
    "EpisodeResult": (
        (0, "episode_title", "string", False, "prim"),
        (1, "story_type", "StoryTypes", False, "enum"),
        (2, "episode_order", "int", False, "prim"),
        (3, "episode_detail_asset_source", "string", False, "prim"),
    ),
    "EventBoxGachaRollResult": (
        (0, "received_things", "ReceivedThing", True, "model"),
        (1, "has_reset", "bool", False, "prim"),
        (2, "drawn_event_box_gacha_box_thing_master_ids", "long", True, "prim"),
    ),
    "EventResult": (
        (0, "acquired_event_point", "int", False, "prim"),
        (1, "attached_story_event_master_id", "long", False, "prim"),
        (2, "circle_event_high_score", "long", False, "prim"),
        (3, "circle_event_high_score_multiplier_percent", "int", False, "prim"),
        (4, "circle_event_before_high_score", "long", False, "prim"),
        (5, "high_score_before", "long", False, "prim"),
        (6, "high_score_after", "long", False, "prim"),
        (7, "before_rank", "long", False, "prim"),
        (8, "after_rank", "long", False, "prim"),
        (9, "story_event_master_id", "long", False, "prim"),
        (10, "event_master_id", "long", False, "prim"),
        (11, "this_time_support_point", "int", False, "prim"),
        (12, "camp_before_rank", "long", False, "prim"),
        (13, "camp_after_rank", "long", False, "prim"),
    ),
    "ExchangeShopThingPayload": (
        (0, "m_exchange_shop_thing_id", "long", False, "prim"),
        (1, "quantity", "int", False, "prim"),
    ),
    "FavoriteStampOrderPayload": ((0, "stamp_master_ids", "long", True, "prim"),),
    "FinishAnotherNotationLivePayload": (
        (0, "base_score_blocks", "BaseScoreBlock", True, "model"),
        (1, "sense_score_blocks", "SenseScoreBlock", True, "model"),
        (2, "star_act_score_blocks", "StarActScoreBlock", True, "model"),
        (
            3,
            "multi_live_additional_score_blocks",
            "MultiLiveAdditionalScoreBlock",
            True,
            "model",
        ),
        (4, "another_notation_master_id", "long", False, "prim"),
        (5, "is_auto_play", "bool", False, "prim"),
    ),
    "FinishLessonPayload": (
        (0, "score", "long", False, "prim"),
        (1, "max_combo", "int", False, "prim"),
        (2, "judges", "NoteJudgePayload", True, "model"),
    ),
    "FinishLivePayload": (
        (0, "score", "long", False, "prim"),
        (1, "max_combo", "int", False, "prim"),
        (2, "judges", "NoteJudgePayload", True, "model"),
        (3, "is_cleared", "bool", False, "prim"),
        (4, "base_score_blocks", "BaseScoreBlock", True, "model"),
        (5, "sense_score_blocks", "SenseScoreBlock", True, "model"),
        (6, "star_act_score_blocks", "StarActScoreBlock", True, "model"),
        (
            7,
            "multi_live_additional_score_blocks",
            "MultiLiveAdditionalScoreBlock",
            True,
            "model",
        ),
        (8, "triple_cast_party_scores", "TripleCastPartyScore", True, "model"),
        (
            9,
            "trial_party_event_stage_result",
            "TrialPartyEventStageResult",
            False,
            "model",
        ),
    ),
    "FinishLiveResult": (
        (1, "league_rewards", "ReceivedThing", True, "model"),
        (2, "rate_result", "RateResult", False, "model"),
        (3, "player_rank_point_result", "PlayerRankPointResult", False, "model"),
        (5, "clear_lamp", "ClearLamps", False, "enum"),
        (6, "rate_grade", "AchievementRateGrades", False, "enum"),
        (8, "is_high_score", "bool", False, "prim"),
        (9, "audition_before_phase", "byte", False, "prim"),
        (10, "audition_after_phase", "byte", False, "prim"),
        (11, "audition_rewards", "ReceivedThing", True, "model"),
        (12, "story_event_rewards", "ReceivedThing", True, "model"),
        (13, "achievement_rate_average", "double", False, "prim"),
        (14, "audition_master_id", "long", False, "prim"),
        (16, "sp_rate_update_result", "SpRateUpdateResult", False, "model"),
        (17, "tournament_result", "TournamentResult", False, "model"),
        (18, "celling_max_count", "int", False, "prim"),
        (19, "celling_user_count", "int", False, "prim"),
        (20, "before_clear_lamp", "ClearLamps", False, "enum"),
        (21, "poster_drop_up_percent", "int", False, "prim"),
        (22, "event_result", "EventResult", False, "model"),
        (23, "live_drop_things", "LiveDropThing", True, "model"),
        (24, "lesson_result", "LessonResult", False, "model"),
        (25, "league_result", "LeagueResult", False, "model"),
        (26, "concert_result", "ConcertResult", False, "model"),
        (27, "bonus_live_result", "BonusLiveResult", False, "model"),
        (28, "ghost_live_result", "GhostLiveResult", False, "model"),
        (29, "trial_party_event_result", "TrialPartyEventResult", False, "model"),
        (
            30,
            "accessory_auto_sell_convert_things",
            "AccessoryAutoSellConvertThing",
            True,
            "model",
        ),
    ),
    "FlashSaleReadStagePayload": (
        (0, "read_flash_sale_stage_ids", "long", True, "prim"),
    ),
    "FriendAcceptResult": (
        (0, "result_status", "FriendAcceptResultStatus", False, "enum"),
    ),
    "FriendFavoritePayload": (
        (0, "target_user_id", "string", False, "prim"),
        (1, "set_favorite", "bool", False, "prim"),
    ),
    "FriendInvitationMissionPayload": (
        (0, "friend_invitation_mission_master_ids", "long", True, "prim"),
    ),
    "FriendInvitationUserInfoResult": (
        (0, "hashed_user_id", "string", False, "prim"),
        (1, "name", "string", False, "prim"),
        (2, "player_rank", "long", False, "prim"),
        (3, "result_status", "InvitationCodeResultStatuses", False, "enum"),
    ),
    "FriendListResult": (
        (0, "results", "FriendResult", True, "model"),
        (1, "current_friend_count", "int", False, "prim"),
    ),
    "FriendRequestResult": (
        (0, "result_status", "FriendRequestResultStatus", False, "enum"),
    ),
    "FriendResult": (
        (0, "user_id", "string", False, "prim"),
        (2, "player_rank", "int", False, "prim"),
        (3, "trophy_master_id1", "long", False, "prim"),
        (4, "trophy_master_id2", "long", False, "prim"),
        (5, "trophy_master_id3", "long", False, "prim"),
        (6, "introduction", "string", False, "prim"),
        (7, "last_logged_in_at", "DateTime", False, "prim"),
        (8, "name", "string", False, "prim"),
        (9, "player_rate", "double", False, "prim"),
        (10, "is_public_player_rate", "bool", False, "prim"),
        (11, "league_class", "LeagueClassTypes", False, "enum"),
        (12, "character_ranks", "CharacterRank", True, "model"),
        (13, "is_public_album_main_page", "bool", False, "prim"),
        (15, "main_character_master_id", "long", False, "prim"),
        (16, "display_awakening_status", "bool", False, "prim"),
        (17, "icon_frame_master_id", "long", False, "prim"),
        (18, "is_favorite", "bool", False, "prim"),
    ),
    "FriendSearchResult": (
        (0, "friend_result", "FriendResult", False, "model"),
        (1, "result_status", "FriendSearchResultStatus", False, "enum"),
    ),
    "GachaHistoryResult": (
        (0, "master_id", "long", False, "prim"),
        (1, "created_at", "DateTime", False, "prim"),
    ),
    "GachaInfoResult": (
        (0, "id_", "long", False, "prim"),
        (1, "roll_limits", "GachaRollLimit", True, "model"),
        (2, "normal_emission_flags", "GachaEmissionFlags", False, "enum"),
        (3, "fixed_emission_flags", "GachaEmissionFlags", False, "enum"),
    ),
    "GachaLineupItemProbability": (
        (0, "id_", "long", False, "prim"),
        (2, "probability", "double", False, "prim"),
    ),
    "GachaRollLimit": (
        (0, "gacha_detail_master_id", "long", False, "prim"),
        (1, "roll_left", "int", False, "prim"),
    ),
    "GachaRollResult": (
        (0, "m_gacha_master_id", "long", False, "prim"),
        (1, "received_things", "GachaThingResult", True, "model"),
        (2, "received_bonus_things", "ReceivedThing", True, "model"),
        (3, "received_detail_bonus_things", "ReceivedThing", True, "model"),
        (4, "received_roll_bonus_things", "ReceivedThing", True, "model"),
    ),
    "GachaSelectedThingsResult": (
        (0, "selected_gacha_thing_ids", "long", True, "prim"),
    ),
    "GachaThingResult": (
        (0, "received_things", "ReceivedThing", True, "model"),
        (1, "additional_received_things", "ReceivedThing", True, "model"),
        (2, "movie_costume_master_id", "long", False, "prim"),
    ),
    "GenerateLotteryResultPayload": (
        (0, "prize", "int", False, "prim"),
        (1, "amount", "int", False, "prim"),
    ),
    "GeneratePhotoPayload": (
        (0, "character_base_master_id", "long", False, "prim"),
        (1, "item_master_id", "long", False, "prim"),
        (2, "image_data", "byte", True, "prim"),
        (3, "thumbnail_image_data", "byte", True, "prim"),
        (4, "appeared_characters", "PhotoAppearedCharacter", True, "model"),
    ),
    "GeneratePhotoResult": (
        (0, "photo_id", "long", False, "prim"),
        (1, "file_name", "string", False, "prim"),
        (2, "sas_token", "string", False, "prim"),
        (3, "rarity", "PhotoRarities", False, "enum"),
        (4, "sign_master_id", "long", False, "prim"),
        (5, "photo_effect_master_id", "long", False, "prim"),
    ),
    "GeneratePhotosPayload": ((0, "payloads", "GeneratePhotoPayload", True, "model"),),
    "GhostLiveInfo": (
        (0, "leader_position", "int", False, "prim"),
        (1, "party_slot", "PartySlotDetail", True, "model"),
    ),
    "GhostLiveResult": (
        (0, "ghost_user_profile", "UserProfileDetail", False, "model"),
        (1, "ghost_user_score", "long", False, "prim"),
        (2, "total_battle_win_count", "long", False, "prim"),
        (3, "matching_result", "MatchingResult", False, "enum"),
        (4, "display_character_master_id", "long", False, "prim"),
        (5, "display_character_awakening_status", "bool", False, "prim"),
    ),
    "HighScoreBuff": (
        (0, "user_id", "string", False, "prim"),
        (1, "buffs", "HighScoreBuffSetting", True, "model"),
    ),
    "HighScoreBuffSetting": (
        (0, "story_event_high_score_buff_setting_id", "long", False, "prim"),
        (1, "current_level", "int", False, "prim"),
    ),
    "HighScoreParty": (
        (0, "user_id", "string", False, "prim"),
        (1, "user_name", "string", False, "prim"),
        (2, "party_name", "string", False, "prim"),
        (3, "slots", "HighScorePartySlot", True, "model"),
        (4, "difficulty", "MusicDifficulties", False, "enum"),
        (5, "leader_position", "int", False, "prim"),
    ),
    "HighScorePartySlot": (
        (0, "position", "int", False, "prim"),
        (1, "character_master_id", "long", False, "prim"),
        (2, "character_level", "int", False, "prim"),
        (3, "character_talent_stage", "int", False, "prim"),
        (4, "character_awakening_phase", "int", False, "prim"),
        (5, "poster_master_id", "long", False, "prim"),
        (6, "poster_level", "int", False, "prim"),
        (7, "poster_breakthrough_phase", "int", False, "prim"),
        (8, "accessory_master_id", "long", False, "prim"),
        (9, "accessory_level", "int", False, "prim"),
        (10, "current_status", "Status", False, "model"),
        (11, "character_display_awakening_status", "bool", False, "prim"),
    ),
    "InboxReceiveResult": (
        (0, "received_things", "ReceivedThing", True, "model"),
        (1, "has_not_receive_things", "bool", False, "prim"),
    ),
    "InviteMultiRoomPayload": ((0, "hashed_user_ids", "string", True, "prim"),),
    "JoinMultiRoomPayload": (
        (0, "hashed_room_id", "string", False, "prim"),
        (1, "password", "string", False, "prim"),
    ),
    "LeaguePartyAndRankingResult": (
        (0, "rank", "int", False, "prim"),
        (1, "user_id", "string", False, "prim"),
        (2, "best_score", "long", False, "prim"),
        (3, "league_master_id", "long", False, "prim"),
        (4, "class_type", "LeagueClassTypes", False, "enum"),
        (5, "user_name", "string", False, "prim"),
        (6, "acting_ability", "int", False, "prim"),
        (7, "slots", "LeaguePartySlotResult", True, "model"),
        (8, "difficulty", "MusicDifficulties", False, "enum"),
    ),
    "LeaguePartySlotResult": (
        (0, "slot_position", "int", False, "prim"),
        (1, "character_master_id", "long", False, "prim"),
        (2, "attribute", "Attributes", False, "enum"),
        (4, "character_rarity", "CharacterRarities", False, "enum"),
        (6, "character_level", "int", False, "prim"),
        (7, "poster_master_id", "long", False, "prim"),
        (8, "poster_rarity", "PossessionRarities", False, "enum"),
        (9, "poster_level", "int", False, "prim"),
        (10, "poster_breakthrough_phase", "int", False, "prim"),
        (11, "accessory_master_id", "long", False, "prim"),
        (12, "accessory_rarity", "PossessionRarities", False, "enum"),
        (13, "accessory_level", "int", False, "prim"),
        (14, "current_status", "Status", False, "model"),
        (15, "position", "int", False, "prim"),
        (16, "character_talent_stage", "int", False, "prim"),
        (17, "character_awakening_phase", "int", False, "prim"),
        (18, "character_display_awakening_status", "bool", False, "prim"),
    ),
    "LeagueReceiveResults": (
        (0, "class_reward_received_things", "ReceivedThing", True, "model"),
        (1, "class_reward_type", "LeagueClassChangeTypes", False, "enum"),
        (2, "first_achieve_received_things", "ReceivedThing", True, "model"),
        (3, "group_rank_received_things", "ReceivedThing", True, "model"),
        (4, "is_first_time_enrolled_class", "bool", False, "prim"),
        (5, "all_class_global_rank_received_things", "ReceivedThing", True, "model"),
    ),
    "LeagueResult": (
        (0, "before_group_ranking", "int", False, "prim"),
        (1, "after_group_ranking", "int", False, "prim"),
        (2, "lowest_up_border_score", "long", False, "prim"),
        (3, "lowest_keep_border_score", "long", False, "prim"),
        (4, "enrolled_group_number", "int", False, "prim"),
        (5, "is_in_counting", "bool", False, "prim"),
    ),
    "LeagueTopMenuInformationResult": (
        (0, "display_start_at", "DateTime", False, "prim"),
        (1, "counting_start_at", "DateTime", False, "prim"),
        (2, "display_end_at", "DateTime", False, "prim"),
        (3, "music_master_id", "long", False, "prim"),
        (6, "league_group_ranking", "int", False, "prim"),
        (8, "up_class_border_score", "long", False, "prim"),
        (9, "up_class_border_ranking", "int", False, "prim"),
        (10, "keep_class_border_score", "long", False, "prim"),
        (11, "keep_class_border_ranking", "int", False, "prim"),
        (12, "group_lowest_rank", "int", False, "prim"),
        (13, "is_participated", "bool", False, "prim"),
        (14, "enrolled_group_number", "int", False, "prim"),
    ),
    "LessonResult": (
        (0, "character_base_master_id", "long", False, "prim"),
        (1, "star_point_result", "StarPointResult", False, "model"),
        (2, "high_score_rewards", "ReceivedThing", True, "model"),
        (3, "high_score_before", "long", False, "prim"),
        (4, "high_score_after", "long", False, "prim"),
    ),
    "LevelUpPhotoPayload": (
        (0, "photo_id", "long", False, "prim"),
        (1, "after_level", "int", False, "prim"),
    ),
    "LevelUpPhotoResult": (
        (0, "photo_id", "long", False, "prim"),
        (1, "before_level", "int", False, "prim"),
        (2, "after_level", "int", False, "prim"),
    ),
    "LiveDropThing": (
        (0, "received_thing", "ReceivedThing", False, "model"),
        (1, "order", "long", False, "prim"),
        (2, "live_drop_type", "LiveDropTypes", False, "enum"),
        (3, "is_fixed_drop", "bool", False, "prim"),
    ),
    "LiveTimeEvent": (
        (0, "timings", "SenseTimingEvent", True, "model"),
        (1, "cool_times", "SenseCoolTime", True, "model"),
    ),
    "LiveUnit": (
        (0, "actors", "Dictionary", False, "model"),
        (1, "time_events", "Dictionary", False, "model"),
        (2, "possible_senses", "Sense", True, "model"),
        (3, "start_effects", "Effect", True, "model"),
        (4, "star_act", "StarAct", False, "model"),
        (5, "total_status", "int", False, "prim"),
        (6, "star_act_sense_light_count", "int", False, "prim"),
        (7, "max_principal", "int", False, "prim"),
        (8, "is_first_play_olivier", "bool", False, "prim"),
        (9, "base_score_percentage", "int", False, "prim"),
        (10, "base_score_difficulty_auto_coefficient", "double", False, "prim"),
        (11, "u_active_live_id", "long", False, "prim"),
    ),
    "LiveUnitWithOrder": (
        (0, "actors", "Dictionary", False, "model"),
        (1, "time_events", "Dictionary", False, "model"),
        (2, "possible_senses", "Sense", True, "model"),
        (3, "start_effects", "Effect", True, "model"),
        (4, "star_act", "StarAct", False, "model"),
        (5, "total_status", "int", False, "prim"),
        (6, "star_act_sense_light_count", "int", False, "prim"),
        (7, "max_principal", "int", False, "prim"),
        (8, "is_first_play_olivier", "bool", False, "prim"),
        (9, "base_score_percentage", "int", False, "prim"),
        (10, "base_score_difficulty_auto_coefficient", "double", False, "prim"),
        (11, "u_active_live_id", "long", False, "prim"),
        (12, "order", "int", False, "prim"),
    ),
    "LoginBonusDetail": (
        (0, "thing_type", "ThingTypes", False, "enum"),
        (1, "thing_id", "long", False, "prim"),
        (2, "thing_quantity", "int", False, "prim"),
        (3, "login_count", "int", False, "prim"),
    ),
    "LoginBonusResult": (
        (0, "login_bonus_id", "long", False, "prim"),
        (1, "current_login_count", "int", False, "prim"),
        (2, "received_things", "ReceivedThing", True, "model"),
        (3, "title", "string", False, "prim"),
        (4, "type", "LoginBonusTypes", False, "enum"),
        (5, "start_date", "DateTime", False, "prim"),
        (6, "end_date", "DateTime", False, "prim"),
        (10, "message_template", "string", False, "prim"),
        (11, "background_image_path", "string", False, "prim"),
        (12, "cardboard_image_path", "string", False, "prim"),
        (13, "logo_image_path", "string", False, "prim"),
        (14, "total_days", "int", False, "prim"),
        (15, "is_loop", "bool", False, "prim"),
        (16, "order", "int", False, "prim"),
        (17, "details", "LoginBonusDetail", True, "model"),
        (18, "navigation_spine_id", "string", False, "prim"),
        (19, "voice_asset_id", "string", False, "prim"),
        (20, "head_motion_master_id", "long", False, "prim"),
        (21, "facial_expression_master_id", "long", False, "prim"),
        (22, "head_direction_master_id", "long", False, "prim"),
        (23, "body_motion_master_id", "long", False, "prim"),
        (24, "lip_sync_master_id", "long", False, "prim"),
        (25, "layout_type", "LoginBonusLayoutTypes", False, "enum"),
        (26, "comeback_campaign_master_id", "long", False, "prim"),
        (27, "login_bonus_spine_group", "LoginBonusSpineGroup", False, "model"),
    ),
    "LoginBonusSpineDetail": (
        (0, "target_value1", "long", False, "prim"),
        (1, "target_value2", "long", False, "prim"),
        (2, "message_template", "string", False, "prim"),
        (3, "navigation_spine_id", "string", False, "prim"),
        (4, "voice_asset_id", "string", False, "prim"),
        (5, "head_motion_master_id", "long", False, "prim"),
        (6, "facial_expression_master_id", "long", False, "prim"),
        (7, "head_direction_master_id", "long", False, "prim"),
        (8, "body_motion_master_id", "long", False, "prim"),
        (9, "lip_sync_master_id", "long", False, "prim"),
    ),
    "LoginBonusSpineGroup": (
        (0, "spine_select_type", "LoginBonusSpineSelectType", False, "enum"),
        (1, "details", "LoginBonusSpineDetail", True, "model"),
    ),
    "LoginPayload": ((0, "push_notification_token", "string", False, "prim"),),
    "LoginResult": (
        (0, "invalided_star_passes", "StarPassTypes", True, "enum"),
        (1, "login_pass_notification", "LoginPassNotificationTypes", False, "enum"),
        (2, "is_approaching_login_pass_invalided", "bool", False, "prim"),
        (3, "invalided_item_master_ids", "long", True, "prim"),
        (4, "approaching_item_master_ids", "long", True, "prim"),
        (
            5,
            "story_event_point_exchange_result",
            "StoryEventPointExchangeResult",
            True,
            "model",
        ),
        (6, "invalided_buff_item_master_ids", "long", True, "prim"),
    ),
    "MainCharacter": (
        (0, "character_master_id", "long", False, "prim"),
        (1, "awakening_phase", "int", False, "prim"),
        (2, "talent_stage", "int", False, "prim"),
        (3, "level", "int", False, "prim"),
        (4, "display_awakening_status", "bool", False, "prim"),
    ),
    "MarketResult": (
        (0, "things", "MarketThing", True, "model"),
        (1, "required_jewel_for_refresh", "int", False, "prim"),
    ),
    "MarketThing": (
        (0, "frame_number", "long", False, "prim"),
        (1, "market_frame_thing_master_id", "long", False, "prim"),
        (4, "has_purchased", "bool", False, "prim"),
        (5, "discount_percent", "int", False, "prim"),
    ),
    "MasterDataManifest": (
        (0, "uri", "string", False, "prim"),
        (1, "sas_token", "string", False, "prim"),
        (2, "version", "string", False, "prim"),
        (3, "publish_timestamp", "long", False, "prim"),
    ),
    "MatchingGhostLiveResult": (
        (0, "ghost_live_master_id", "long", False, "prim"),
        (1, "ghost_user_profile", "UserProfileDetail", False, "model"),
        (2, "ghost_live_info", "GhostLiveInfo", False, "model"),
    ),
    "MissionPassRewardsResult": (
        (0, "mission_pass_rewards", "ReceivedThing", True, "model"),
        (1, "reward_result", "MissionPassRewardStatus", False, "enum"),
    ),
    "MultiLiveAdditionalScoreBlock": (
        (0, "hash", "long", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "life", "int", False, "prim"),
        (3, "time_event_second", "int", False, "prim"),
        (4, "combo", "int", False, "prim"),
    ),
    "MultiLiveInformation": ((0, "scores", "Dictionary", False, "model"),),
    "MultiRoomCreateResult": (
        (0, "hashed_multi_room_id", "string", False, "prim"),
        (1, "room_detail", "MultiRoomDetailResult", False, "model"),
    ),
    "MultiRoomDetailResult": (
        (
            0,
            "multi_room_information_result",
            "MultiRoomInformationResult",
            False,
            "model",
        ),
        (1, "multi_room_rankings", "MultiRoomRanking", True, "model"),
        (2, "is_finished", "bool", False, "prim"),
        (3, "password", "string", False, "prim"),
    ),
    "MultiRoomInformationResult": (
        (0, "hashed_multi_room_id", "string", False, "prim"),
        (1, "room_name", "string", False, "prim"),
        (2, "play_mode", "MultiRoomPlayModes", False, "enum"),
        (3, "joined_member_count", "int", False, "prim"),
        (4, "can_join_max_member", "int", False, "prim"),
        (5, "start_date", "DateTime", False, "prim"),
        (6, "end_date", "DateTime", False, "prim"),
        (7, "live_master_id1", "long", False, "prim"),
        (8, "live_master_id2", "long", False, "prim"),
        (9, "live_master_id3", "long", False, "prim"),
        (10, "has_password", "bool", False, "prim"),
    ),
    "MultiRoomInvitedResult": (
        (0, "owner_user_name", "string", False, "prim"),
        (
            1,
            "multi_room_information_result",
            "MultiRoomInformationResult",
            False,
            "model",
        ),
    ),
    "MultiRoomJoinnedResult": (
        (0, "my_rank", "int", False, "prim"),
        (1, "my_score", "long", False, "prim"),
        (2, "my_total_achievement_rate_percent_record", "Decimal", False, "model"),
        (
            3,
            "multi_room_information_result",
            "MultiRoomInformationResult",
            False,
            "model",
        ),
    ),
    "MultiRoomPartySlot": (
        (0, "position", "int", False, "prim"),
        (1, "character_master_id", "long", False, "prim"),
        (2, "character_level", "int", False, "prim"),
        (3, "character_talent_stage", "int", False, "prim"),
        (4, "character_awakening_phase", "int", False, "prim"),
        (5, "character_display_awakening_status", "bool", False, "prim"),
        (6, "poster_master_id", "long", False, "prim"),
        (7, "poster_level", "int", False, "prim"),
        (8, "poster_breakthrough_phase", "int", False, "prim"),
        (9, "accessory_master_id", "long", False, "prim"),
        (10, "accessory_level", "int", False, "prim"),
        (11, "u_accessory_id", "long", False, "prim"),
        (12, "current_status", "Status", False, "model"),
    ),
    "MultiRoomRanking": (
        (0, "user_id", "string", False, "prim"),
        (1, "rank", "int", False, "prim"),
        (2, "is_owner", "bool", False, "prim"),
        (3, "score", "long", False, "prim"),
        (4, "total_achievement_rate_percent_record", "Decimal", False, "model"),
        (5, "best_record_challenge_count", "int", False, "prim"),
        (6, "best_record_date", "DateTime", False, "prim"),
        (7, "user_profile", "UserProfile", False, "model"),
        (8, "party_info", "PartyInfo", False, "model"),
        (9, "note_result", "NoteResult", False, "model"),
    ),
    "MusicCourseRandomSelectResult": (
        (0, "details", "MusicCourseRandomSelectResultDetail", True, "model"),
    ),
    "MusicCourseRandomSelectResultDetail": (
        (0, "set_list_number", "int", False, "prim"),
        (1, "live_master_id", "long", False, "prim"),
    ),
    "MusicCourseRankingPayload": (
        (0, "user_id", "long", False, "prim"),
        (1, "current_challenge_count", "int", False, "prim"),
        (2, "perfect_star", "int", False, "prim"),
        (3, "perfect", "int", False, "prim"),
        (4, "great", "int", False, "prim"),
        (5, "good", "int", False, "prim"),
        (6, "bad", "int", False, "prim"),
        (7, "miss", "int", False, "prim"),
        (8, "total_achievement_rate_percent_record", "Decimal", False, "model"),
        (9, "best_record_challenge_count", "int", False, "prim"),
        (10, "best_record_date", "DateTime", False, "prim"),
    ),
    "MyCircleInformationResult": (
        (0, "u_circle_hashed_id", "string", False, "prim"),
        (1, "name", "string", False, "prim"),
        (2, "comment", "string", False, "prim"),
        (3, "play_time_start_type", "PlayTimeTypes", False, "enum"),
        (4, "play_time_end_type", "PlayTimeTypes", False, "enum"),
        (5, "entry_type", "EntryTypes", False, "enum"),
        (6, "member_count", "int", False, "prim"),
        (7, "my_authority", "CircleAuthorities", False, "enum"),
        (8, "result_status", "CircleResultStatus", False, "enum"),
        (9, "circle_banner", "CircleBanner", False, "model"),
        (10, "company_master_id", "long", False, "prim"),
        (11, "character_base_master_id", "long", False, "prim"),
        (
            12,
            "support_company_information",
            "SupportCompanyInformation",
            False,
            "model",
        ),
        (13, "support_company", "Companies", False, "enum"),
        (14, "daily_added_support_point", "int", False, "prim"),
        (15, "is_publish_ranking", "bool", False, "prim"),
        (16, "stamina_last_received_at", "DateTime", False, "prim"),
        (
            17,
            "circle_authority_update_type",
            "CircleAuthorityUpdateTypes",
            False,
            "enum",
        ),
    ),
    "NoteJudgePayload": (
        (0, "timing", "TimingTypes", False, "enum"),
        (1, "count", "int", False, "prim"),
    ),
    "NoteResult": (
        (0, "perfect_star", "int", False, "prim"),
        (1, "perfect", "int", False, "prim"),
        (2, "great", "int", False, "prim"),
        (3, "good", "int", False, "prim"),
        (4, "bad", "int", False, "prim"),
        (5, "miss", "int", False, "prim"),
    ),
    "NotificationContentResult": (
        (0, "id_", "long", False, "prim"),
        (1, "body", "string", False, "prim"),
        (2, "title", "string", False, "prim"),
        (3, "posting_at", "DateTime", False, "prim"),
        (4, "last_updated_at", "DateTime", False, "prim"),
        (5, "notification_tab_category", "NotificationTabCategory", False, "enum"),
        (6, "notification_category", "NotificationCategory", False, "enum"),
        (7, "banner_path", "string", False, "prim"),
    ),
    "NotificationResult": (
        (0, "id_", "long", False, "prim"),
        (1, "banner_path", "string", False, "prim"),
        (2, "title", "string", False, "prim"),
        (3, "posting_at", "DateTime", False, "prim"),
        (4, "last_updated_at", "DateTime", False, "prim"),
        (5, "notification_tab_category", "NotificationTabCategory", False, "enum"),
        (6, "notification_category", "NotificationCategory", False, "enum"),
        (7, "is_confirmation", "bool", False, "prim"),
        (8, "order", "int", False, "prim"),
    ),
    "PartyInfo": (
        (0, "leader_position", "int", False, "prim"),
        (1, "multi_room_party_slots", "MultiRoomPartySlot", True, "model"),
    ),
    "PartyPayload": (
        (0, "leader_position", "int", False, "prim"),
        (1, "party_slot_payload", "PartySlotPayload", True, "model"),
    ),
    "PartySlotAccessoryPayload": (
        (0, "m_accessory_id", "long", False, "prim"),
        (1, "level", "int", False, "prim"),
        (2, "m_accessory_effect_id1", "long", False, "prim"),
        (3, "m_accessory_effect_id2", "long", False, "prim"),
        (4, "m_accessory_effect_id3", "long", False, "prim"),
    ),
    "PartySlotCharacterPayload": (
        (0, "m_character_id", "long", False, "prim"),
        (1, "talent_stage", "int", False, "prim"),
        (2, "awakening_phase", "int", False, "prim"),
        (3, "level", "int", False, "prim"),
        (4, "sense_level", "int", False, "prim"),
        (5, "current_experience", "int", False, "prim"),
        (6, "released_episode_order", "CharacterEpisodeOrder", False, "enum"),
        (7, "read_episode_order", "CharacterEpisodeOrder", False, "enum"),
        (8, "display_awakening_status", "bool", False, "prim"),
    ),
    "PartySlotDetail": (
        (0, "position", "int", False, "prim"),
        (1, "character_master_id", "long", False, "prim"),
        (2, "character_level", "int", False, "prim"),
        (3, "character_talent_stage", "int", False, "prim"),
        (4, "character_awakening_phase", "int", False, "prim"),
        (5, "character_display_awakening_status", "bool", False, "prim"),
        (6, "poster_master_id", "long", False, "prim"),
        (7, "poster_level", "int", False, "prim"),
        (8, "poster_breakthrough_phase", "int", False, "prim"),
        (9, "accessory_master_id", "long", False, "prim"),
        (10, "accessory_level", "int", False, "prim"),
        (11, "current_status_vocal", "int", False, "prim"),
        (12, "current_status_expression", "int", False, "prim"),
        (13, "current_status_concentration", "int", False, "prim"),
        (14, "u_accessory_id", "long", False, "prim"),
    ),
    "PartySlotPayload": (
        (0, "position", "int", False, "prim"),
        (
            1,
            "party_slot_character_payload",
            "PartySlotCharacterPayload",
            False,
            "model",
        ),
        (2, "party_slot_poster_payload", "PartySlotPosterPayload", False, "model"),
        (
            3,
            "party_slot_accessory_payload",
            "PartySlotAccessoryPayload",
            False,
            "model",
        ),
    ),
    "PartySlotPosterPayload": (
        (0, "m_poster_id", "long", False, "prim"),
        (1, "level", "int", False, "prim"),
        (2, "phase", "int", False, "prim"),
        (3, "released_episode", "PosterEpisodeTypes", False, "enum"),
    ),
    "PhotoAppearedCharacter": (
        (0, "character_base_master_id", "long", False, "prim"),
        (1, "is_main_character", "bool", False, "prim"),
    ),
    "PlayerRankPointResult": (
        (0, "rank_before", "int", False, "prim"),
        (1, "rank_after", "int", False, "prim"),
        (2, "rank_point_before", "int", False, "prim"),
        (3, "rank_point_after", "int", False, "prim"),
        (4, "rank_point_acquired", "int", False, "prim"),
        (5, "stamina_before", "int", False, "prim"),
    ),
    "PosterAlternativeImagePayload": (
        (0, "poster_id", "long", False, "prim"),
        (1, "pattern", "int", False, "prim"),
    ),
    "PosterFavoritePayload": (
        (0, "poster_id", "long", False, "prim"),
        (1, "set_favorite", "bool", False, "prim"),
    ),
    "PosterLineupResult": (
        (0, "normal_probabilities", "PosterRarityProbability", True, "model"),
        (1, "fixed_probabilities", "PosterRarityProbability", True, "model"),
        (2, "normal_lineup_items", "GachaLineupItemProbability", True, "model"),
        (3, "fixed_lineup_items", "GachaLineupItemProbability", True, "model"),
    ),
    "PosterRarityProbability": (
        (0, "rarity", "PossessionRarities", False, "enum"),
        (1, "probability", "double", False, "prim"),
    ),
    "ProcessPaymentResult": (
        (0, "result", "ProcessPaymentTransactionResult", False, "enum"),
    ),
    "PurchaseItemPayload": ((0, "m_jewel_shop_item_id", "long", False, "prim"),),
    "RateResult": (
        (0, "achievement_rate_result", "RateUpdateResult", False, "model"),
        (1, "live_rate_result", "RateUpdateResult", False, "model"),
        (2, "total_rate_before", "double", False, "prim"),
        (3, "total_rate_after", "double", False, "prim"),
    ),
    "RateUpdateResult": (
        (0, "best_ever", "double", False, "prim"),
        (1, "this_time", "double", False, "prim"),
    ),
    "RawHighScoreRankingResult": (
        (0, "raw_ranking", "RawRankingWithLongPoint", True, "model"),
        (1, "high_score_parties", "HighScoreParty", True, "model"),
        (2, "high_score_buffs", "HighScoreBuff", True, "model"),
        (3, "user_profiles", "UserProfile", True, "model"),
    ),
    "RawRanking": (
        (0, "rank", "int", False, "prim"),
        (1, "point", "int", False, "prim"),
        (2, "user_id", "string", False, "prim"),
        (3, "group_value", "int", False, "prim"),
    ),
    "RawRankingResult": (
        (0, "raw_ranking", "RawRanking", True, "model"),
        (1, "user_profiles", "UserProfile", True, "model"),
    ),
    "RawRankingWithLongPoint": (
        (0, "rank", "int", False, "prim"),
        (1, "point", "long", False, "prim"),
        (2, "user_id", "string", False, "prim"),
    ),
    "ReadNotificationPayload": (
        (0, "tab_category", "NotificationTabCategory", False, "enum"),
        (1, "read_at", "DateTime", False, "prim"),
    ),
    "ReceivedThing": (
        (0, "type", "ThingTypes", False, "enum"),
        (1, "id_", "long", False, "prim"),
        (2, "quantity", "int", False, "prim"),
        (3, "original_type", "ThingTypes", False, "enum"),
        (4, "original_id", "long", False, "prim"),
        (5, "after_phase", "int", False, "prim"),
        (6, "sent_inbox", "bool", False, "prim"),
    ),
    "RegisterAppStorePaymentPayload": ((0, "receipt_base64", "string", False, "prim"),),
    "RegisterBirthDayPayload": ((0, "birth_date", "DateTime", False, "prim"),),
    "RegisterGooglePlayPaymentPayload": ((0, "json_", "string", False, "prim"),),
    "RegisterPayload": ((0, "name", "string", False, "prim"),),
    "RegisterTakeOverPasswordPayload": ((0, "password", "string", False, "prim"),),
    "RollResult": (
        (0, "roll_order", "int", False, "prim"),
        (1, "selected_slot", "int", False, "prim"),
        (2, "roulette_prize_master_id", "long", False, "prim"),
    ),
    "RouletteRollResult": ((0, "roll_results", "RollResult", True, "model"),),
    "ScoreWithDateResult": (
        (0, "score", "long", False, "prim"),
        (1, "date", "DateTime", False, "prim"),
    ),
    "SelectMusicCourseRandomMusicPayload": (
        (0, "music_course_master_id", "long", False, "prim"),
        (1, "music_course_gauge_type", "MusicCourseGaugeType", False, "enum"),
    ),
    "SellAccessoryPayload": ((0, "u_accessory_ids", "long", True, "prim"),),
    "Sense": (
        (0, "id_", "long", False, "prim"),
        (1, "actor_id", "long", False, "prim"),
        (3, "cool_time", "int", False, "prim"),
        (4, "sense_type", "SenseTypes", False, "enum"),
        (5, "acquirable_lights", "SenseLightTypes", True, "enum"),
        (6, "pre_sense_effect", "Effect", True, "model"),
        (7, "sense_effect", "SenseEffect", False, "model"),
        (8, "poster_effect", "Effect", True, "model"),
        (9, "accessory_effect", "Effect", True, "model"),
        (10, "combination_sense_id", "long", True, "prim"),
        (11, "sense_master_id", "long", False, "prim"),
        (12, "original_actor_id", "long", False, "prim"),
    ),
    "SenseCoolTime": (
        (0, "position", "int", False, "prim"),
        (1, "cool_time", "int", False, "prim"),
    ),
    "SenseEffect": (
        (0, "score_factor", "int", False, "prim"),
        (1, "principal", "int", False, "prim"),
        (2, "branch_condition", "BranchConditionTypes", False, "enum"),
        (3, "effect_branches", "EffectBranch", True, "model"),
    ),
    "SenseScoreBlock": (
        (0, "hash", "long", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "life", "int", False, "prim"),
        (3, "time_event_second", "int", False, "prim"),
        (4, "sense_id", "long", False, "prim"),
        (5, "combo", "int", False, "prim"),
    ),
    "SenseTimingEvent": (
        (0, "timing_seconds", "int", False, "prim"),
        (1, "position", "int", False, "prim"),
        (2, "event", "TimingEvent", False, "model"),
    ),
    "SetAlbumPublishingPayload": (
        (0, "publishing", "bool", False, "prim"),
        (1, "publish_page_number", "int", False, "prim"),
    ),
    "SetLessonPartyPayload": (
        (0, "slots", "SetLessonPartySlotPayload", True, "model"),
    ),
    "SetLessonPartySlotPayload": (
        (0, "order", "int", False, "prim"),
        (1, "character_id", "long", False, "prim"),
    ),
    "SetPhotoTagPayload": (
        (0, "photo_id", "long", False, "prim"),
        (1, "character_base_ids", "long", True, "prim"),
    ),
    "SetSelectedThingsPayload": ((0, "gacha_thing_ids", "long", True, "prim"),),
    "SpRateUpdateResult": (
        (0, "best_ever", "int", False, "prim"),
        (1, "this_time", "int", False, "prim"),
        (2, "best_ever_total", "int", False, "prim"),
        (3, "this_time_total", "int", False, "prim"),
    ),
    "StarAct": (
        (0, "score_factor", "int", False, "prim"),
        (1, "actor_id", "long", False, "prim"),
        (2, "branch_condition", "BranchConditionTypes", False, "enum"),
        (3, "effect_branches", "EffectBranch", True, "model"),
    ),
    "StarActScoreBlock": (
        (0, "hash", "long", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "life", "int", False, "prim"),
        (3, "time_event_second", "int", False, "prim"),
        (4, "combo", "int", False, "prim"),
    ),
    "StarPointResult": (
        (0, "rank_before", "int", False, "prim"),
        (1, "rank_after", "int", False, "prim"),
        (2, "star_point_before", "int", False, "prim"),
        (3, "star_point_after", "int", False, "prim"),
        (4, "star_point_acquired", "int", False, "prim"),
        (5, "received_reward", "ReceivedThing", True, "model"),
    ),
    "StartLessonPayload": (
        (0, "character_base_master_id", "int", False, "prim"),
        (1, "live_master_id", "long", False, "prim"),
    ),
    "StartLivePayload": (
        (0, "party_id", "long", False, "prim"),
        (1, "live_master_id", "long", False, "prim"),
        (2, "audition_master_id", "long", False, "prim"),
        (3, "league_master_id", "long", False, "prim"),
        (4, "use_stamina", "bool", False, "prim"),
        (5, "stamina_consumption_ratio", "int", False, "prim"),
        (6, "live_setting_master_id", "long", False, "prim"),
        (7, "is_auto_play", "bool", False, "prim"),
        (8, "is_story_event_challenge", "bool", False, "prim"),
        (9, "concert_stage_master_id", "long", False, "prim"),
        (10, "bonus_live_stage_master_id", "long", False, "prim"),
        (11, "music_course_detail_master_id", "long", False, "prim"),
        (12, "music_course_gauge_type", "MusicCourseGaugeType", False, "enum"),
        (13, "ghost_live_master_id", "long", False, "prim"),
        (14, "trial_party_event_stage_master_id", "long", False, "prim"),
    ),
    "StartMultiLivePayload": (
        (0, "live_master_id", "long", False, "prim"),
        (1, "multi_live_id", "long", False, "prim"),
        (2, "use_stamina", "bool", False, "prim"),
        (3, "stamina_consumption_ratio", "int", False, "prim"),
        (4, "party_id", "long", False, "prim"),
    ),
    "StartMultiRoomLivePayload": (
        (0, "hashed_multi_room_id", "string", False, "prim"),
        (1, "live_master_id", "long", False, "prim"),
        (2, "party_id", "long", False, "prim"),
    ),
    "StartTournamentPayload": (
        (0, "tournament_detail_master_id", "long", False, "prim"),
        (1, "party_id", "long", False, "prim"),
        (2, "stamina_consumption_ratio", "int", False, "prim"),
    ),
    "StartTripleCastLivePayload": (
        (0, "m_live_id", "long", False, "prim"),
        (1, "m_triple_cast_id", "long", False, "prim"),
    ),
    "StartTripleCastLiveResult": (
        (0, "live_units", "LiveUnitWithOrder", True, "model"),
    ),
    "Status": (
        (0, "concentration", "int", False, "prim"),
        (1, "expression", "int", False, "prim"),
        (2, "vocal", "int", False, "prim"),
        (3, "total_status", "int", False, "prim"),
    ),
    "StoryEventCampInfo": (
        (0, "raw_ranking", "RawRanking", False, "model"),
        (1, "camp1_total_point", "long", False, "prim"),
        (2, "camp2_total_point", "long", False, "prim"),
    ),
    "StoryEventMissionCircleProgress": (
        (0, "story_event_circle_mission_master_id", "long", False, "prim"),
        (1, "current_count", "int", False, "prim"),
    ),
    "StoryEventMissionCircleProgressResult": (
        (0, "is_success", "bool", False, "prim"),
        (1, "progresses", "StoryEventMissionCircleProgress", True, "model"),
    ),
    "StoryEventPointExchangeResult": (
        (0, "story_event_master_id", "long", False, "prim"),
        (1, "before_story_event_point_amount", "int", False, "prim"),
        (2, "after_coin_amount", "int", False, "prim"),
    ),
    "SupportCompanyInformation": (
        (0, "sirius", "SupportCompanyLevelStatus", False, "model"),
        (1, "eden", "SupportCompanyLevelStatus", False, "model"),
        (2, "gingaza", "SupportCompanyLevelStatus", False, "model"),
        (3, "denki", "SupportCompanyLevelStatus", False, "model"),
    ),
    "SupportCompanyLevelLimitDetail": (
        (0, "order", "int", False, "prim"),
        (1, "quantity", "long", False, "prim"),
    ),
    "SupportCompanyLevelLimitPayload": (
        (0, "company", "Companies", False, "enum"),
        (1, "coin_quantity", "long", False, "prim"),
        (2, "details", "SupportCompanyLevelLimitDetail", True, "model"),
    ),
    "SupportCompanyLevelLimitStatus": (
        (0, "current_coin_quantity", "long", False, "prim"),
        (1, "details", "SupportCompanyLevelLimitStatusDetail", True, "model"),
    ),
    "SupportCompanyLevelLimitStatusDetail": (
        (0, "order", "int", False, "prim"),
        (1, "current_quantity", "long", False, "prim"),
    ),
    "SupportCompanyLevelStatus": (
        (0, "level", "int", False, "prim"),
        (1, "current_support_point", "int", False, "prim"),
        (2, "last_level_upped_at", "DateTime", False, "prim"),
        (3, "level_limit", "int", False, "prim"),
        (4, "level_limit_status", "SupportCompanyLevelLimitStatus", False, "model"),
    ),
    "TakeOverAccountPayload": (
        (0, "linkage_code", "string", False, "prim"),
        (1, "password", "string", False, "prim"),
    ),
    "TakeOverAccountResult": (
        (0, "is_success", "bool", False, "prim"),
        (1, "user_id", "string", False, "prim"),
        (2, "name", "string", False, "prim"),
        (3, "rank", "int", False, "prim"),
        (4, "login_token", "string", False, "prim"),
    ),
    "TakeOverCodeResult": (
        (0, "is_success", "bool", False, "prim"),
        (1, "linkage_code", "string", False, "prim"),
    ),
    "TimedConfirmationCode": (
        (0, "confirmation_code", "string", False, "prim"),
        (1, "remaining_seconds", "int", False, "prim"),
    ),
    "TimingEvent": (
        (0, "total_sense_lights", "SenseLightTypes", True, "enum"),
        (1, "grant_sense_lights", "SenseLightTypes", True, "enum"),
        (2, "is_star_act", "bool", False, "prim"),
        (3, "lost_lights", "bool", False, "prim"),
        (4, "acquirable_lights", "SenseLightTypes", True, "enum"),
        (5, "sense_ids", "long", True, "prim"),
        (6, "sense_voice_ids", "long", True, "prim"),
        (7, "sense_master_id", "long", False, "prim"),
    ),
    "TotalPointEventInformationResult": (
        (0, "current_total_point", "long", False, "prim"),
    ),
    "TotalPointEventRankingResult": (
        (0, "raw_ranking", "RawRankingWithLongPoint", True, "model"),
        (1, "user_profiles", "UserProfile", True, "model"),
    ),
    "TournamentQualifyingInformationResult": (
        (0, "entry_code", "string", False, "prim"),
    ),
    "TournamentResult": (
        (0, "best_ever_unique_score", "long", False, "prim"),
        (1, "this_time_unique_score", "long", False, "prim"),
        (2, "tournament_detail_master_id", "long", False, "prim"),
    ),
    "TransitionTokenResult": ((0, "token", "string", False, "prim"),),
    "TrialPartyEventResult": ((0, "rewards", "ReceivedThing", True, "model"),),
    "TrialPartyEventStageResult": ((0, "principal_gauge_value", "int", False, "prim"),),
    "TripleCastPartyAndRankingResult": (
        (0, "rank", "int", False, "prim"),
        (1, "user_id", "string", False, "prim"),
        (2, "best_score", "long", False, "prim"),
        (3, "triple_cast_master_id", "long", False, "prim"),
        (4, "class_type", "LeagueClassTypes", False, "enum"),
        (5, "difficulty", "MusicDifficulties", False, "enum"),
        (6, "user_name", "string", False, "prim"),
        (7, "parties", "TripleCastPartyResult", True, "model"),
    ),
    "TripleCastPartyResult": (
        (0, "order", "int", False, "prim"),
        (1, "score", "long", False, "prim"),
        (2, "slots", "LeaguePartySlotResult", True, "model"),
    ),
    "TripleCastPartyScore": (
        (0, "order", "int", False, "prim"),
        (1, "score", "long", False, "prim"),
    ),
    "UpdateClearLampResult": ((0, "clear_lamp", "ClearLamps", False, "enum"),),
    "UpdateGameHintPayload": ((0, "categories", "PageCategories", True, "enum"),),
    "UpdateHomeDisplayPreferencePayload": (
        (0, "home_character_base_master_id", "long", False, "prim"),
        (2, "member_character_base_master_id", "long", False, "prim"),
        (3, "story_character_base_master_id", "long", False, "prim"),
        (4, "shop_character_base_master_id", "long", False, "prim"),
        (5, "home_costume_master_id", "long", False, "prim"),
        (7, "member_costume_master_id", "long", False, "prim"),
        (8, "story_costume_master_id", "long", False, "prim"),
        (9, "shop_costume_master_id", "long", False, "prim"),
        (10, "illust_character_master_id", "long", False, "prim"),
        (11, "display_awakening_status", "bool", False, "prim"),
        (12, "home_character_display_type", "HomeCharacterDisplayTypes", False, "enum"),
        (13, "login_bonus_character_base_master_id", "long", False, "prim"),
        (14, "login_bonus_spine_costume_master_id", "long", False, "prim"),
    ),
    "UpdateLastViewedAtPayload": (
        (0, "viewed_shop_category_types", "ViewedShopCategoryTypes", False, "enum"),
        (1, "exchange_shop_master_id", "long", False, "prim"),
    ),
    "UpdateTutorialPayload": ((0, "tutorial_status", "TutorialStatus", False, "enum"),),
    "UrlResult": ((0, "url", "string", False, "prim"),),
    "UseExperienceItemsPayload": (
        (0, "item_master_id", "long", False, "prim"),
        (1, "quantity", "int", False, "prim"),
    ),
    "UseStaminaRecoveryItem": (
        (0, "item_master_id", "long", False, "prim"),
        (1, "quantity", "int", False, "prim"),
    ),
    "UseStaminaRecoveryItemsPayload": (
        (0, "items", "UseStaminaRecoveryItem", True, "model"),
    ),
    "User": (
        (0, "id_", "long", False, "prim"),
        (1, "player_rank", "int", False, "prim"),
        (2, "current_rank_point", "int", False, "prim"),
        (3, "current_stamina", "int", False, "prim"),
        (4, "max_stamina_restored_at", "DateTime", False, "prim"),
        (5, "paid_jewel", "int", False, "prim"),
        (6, "free_jewel", "int", False, "prim"),
        (7, "coin", "int", False, "prim"),
        (8, "player_rank_limit", "int", False, "prim"),
        (9, "stamina_recover_times_with_jewel", "int", False, "prim"),
        (10, "circle_usage_restrictions_end_time", "DateTime", False, "prim"),
        (11, "circle_id", "string", False, "prim"),
        (12, "game_start_at", "DateTime", False, "prim"),
        (13, "hash_user_id", "string", False, "prim"),
        (14, "ban_level", "BanLevels", False, "enum"),
        (15, "tutorial_status", "TutorialStatus", False, "enum"),
        (16, "monthly_payment", "int", False, "prim"),
        (17, "splash_last_displayed_at", "DateTime", False, "prim"),
        (18, "is_caped_player_rank", "bool", False, "prim"),
        (19, "require_caped_player_rank_announce", "bool", False, "prim"),
    ),
    "UserProfile": (
        (0, "user_id", "string", False, "prim"),
        (1, "user_name", "string", False, "prim"),
        (2, "trophy_master_id1", "long", False, "prim"),
        (3, "trophy_master_id2", "long", False, "prim"),
        (4, "trophy_master_id3", "long", False, "prim"),
        (5, "main_m_character_id", "long", False, "prim"),
        (6, "main_character_level", "int", False, "prim"),
        (7, "character_display_awakening_status", "bool", False, "prim"),
        (8, "icon_frame_master_id", "long", False, "prim"),
    ),
    "UserProfileDetail": (
        (0, "user_id", "string", False, "prim"),
        (1, "user_name", "string", False, "prim"),
        (2, "trophy_master_id1", "long", False, "prim"),
        (3, "trophy_master_id2", "long", False, "prim"),
        (4, "trophy_master_id3", "long", False, "prim"),
        (5, "main_m_character_id", "long", False, "prim"),
        (6, "main_character_level", "int", False, "prim"),
        (7, "character_display_awakening_status", "bool", False, "prim"),
        (8, "icon_frame_master_id", "long", False, "prim"),
        (9, "name_color_master_id", "long", False, "prim"),
        (10, "name_base_color_master_id", "long", False, "prim"),
        (11, "nameplate_master_id", "long", False, "prim"),
        (12, "nameplate_detail_master_id", "long", False, "prim"),
    ),
    "UserResult": ((0, "user", "User", False, "model"),),
    "ViewShopResult": ((0, "converted_things", "ConvertedThingResult", True, "model"),),
}
